server:
    port: 8506

turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: jyh-store-cloud-service-admin,jyh-store-cloud-web-admin,jyh-store-cloud-service-search,jyh-store-cloud-web-search,jyh-store-cloud-service-portal,jyh-store-cloud-web-portal,jyh-store-cloud-service-item,jyh-store-cloud-web-item,jyh-store-cloud-service-cart,jyh-store-cloud-web-cart,jyh-store-cloud-service-notify,jyh-store-cloud-web-notify,jyh-store-cloud-service-sso,jyh-store-cloud-web-order,jyh-store-cloud-service-order,jyh-store-cloud-web-cart  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
